### ISSUE TITLE
Wrong units

### ISSUE THREAD

**Issue by PabRod** [gossips/Balance#1]
The units of the figures are wrong. Instead of _cm_ it should read _m_.

Who wants to fix it? I'm looking at you, @elsweinans and @ingridleemput :)

**Comment by ingridleemput** [comment]
I will fix it for you! I will assign it to myself.

**Comment by PabRod** [comment]
I'm reopening it. It's still not fixed.

**Comment by ingridleemput** [comment]
Fixed!
